# This file was generated by GoReleaser. DO NOT EDIT.
cask "gcal-organizer" do
  name "gcal-organizer"
  desc "Automate meeting note organization, calendar syncing, and task assignment"
  homepage "https://github.com/jflowers/gcal-organizer"
  version "1.3.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gcal-organizer"
  manpage "man/gcal-organizer.1"

  on_macos do
    on_intel do
      url "https://github.com/jflowers/gcal-organizer/releases/download/v#{version}/gcal-organizer_#{version}_darwin_amd64.tar.gz"
      sha256 "24e3b952b682090fdb84cfdcff7534aa41850e3b5fa797957dcc8ae829e9926c"
    end
    on_arm do
      url "https://github.com/jflowers/gcal-organizer/releases/download/v#{version}/gcal-organizer_#{version}_darwin_arm64.tar.gz"
      sha256 "fc1975a57c8b79fc4f537359d9d9df6234f2adb83c0e9ca9de659c392237d379"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jflowers/gcal-organizer/releases/download/v#{version}/gcal-organizer_#{version}_linux_amd64.tar.gz"
      sha256 "2b67e3f90f5cd1cf98195b6ff76f757148d6abd8e21b7dcc091469ab693c2a42"
    end
    on_arm do
      url "https://github.com/jflowers/gcal-organizer/releases/download/v#{version}/gcal-organizer_#{version}_linux_arm64.tar.gz"
      sha256 "d914f069d0334dddbebfe2aad0fe3a33639863c586812161a3011e6737b9a822"
    end
  end

  # No zap stanza required
end
